### ISSUE TITLE
carrier timestamps timezone differs per status

### ISSUE THREAD

**Issue by MrMoronIV** [Vonage/vonage-php-sdk-core#173]
About SMS delivery reports

the value `$param['scts']` is pushed in different timezones depending on the actual `$param['status']`. For accepted I get  `status=accepted&scts=1905061056` and for delivered I get `status=delivered&scts=1905061256`.

These reports are send in the same minute.

**Comment by mheap** [comment]
Thanks for the report @MrMoronIV. I've shared with our SMS team and will keep you updated as we investigate

**Comment by SecondeJK** [comment]
This is a four-year-old issue, so I am not sure if it is still relevant. Closing for housekeeping, any problems can have a new issue opened
