### ISSUE TITLE
Error response for Calls seems to have changed

### ISSUE THREAD

**Issue by dragonmantank** [Vonage/vonage-php-sdk-core#198]
https://github.com/Nexmo/nexmo-php/blob/df1cd7796790f33cd07f9b50330a80ac35fee67f/src/Call/Call.php#L94

When doing some testing, got a 400 error when attempting to transfer an existing call. I recieved the following HTTP response:

```
{"type":400,"title":"Bad Request","invalid_parameters":[{"reason":"Invalid type parameter provided","name":"destination"}]}
```

but the following PHP error:

```
PHP Notice:  Undefined index: error_title in /home/ctankersley/Projects/nexmo/nexmo-php-code-snippets/voice/inbound-calls-slim/vendor/nexmo/client-core/src/Call/Call.php on line 95
```

The HTTP response doesn't match what the SDK expects, so will need to update the SDK.

**Comment by SecondeJK** [comment]
Calls module is about to be deprecated, which will take this issue with it, so closing for maintenance.
