### ISSUE TITLE
Fetching balance from account results in 401 unauthorized

### ISSUE THREAD

**Issue by codegain** [Vonage/vonage-php-sdk-core#243]
Hi,

Today I updated my whole project (including `nexmo/laravel` from 1.x to 2.x) and now the following call results in 401 unauthorized:

```
 return $this->nexmo->account()->getBalance()->getBalance();
```

I dumped the request and response of the nexmo API and it seems that there is no authorization sent to the `/account/get-balance` endpoint. I debugged this further and got it working after modifying the following function in `vendor/nexmo/client-core/src/Client.php` like so:

```
    protected static function requiresAuthInUrlNotBody(\Psr\Http\Message\RequestInterface $request)
    {
        $path = $request->getUri()->getPath();
        $isRedactEndpoint = strpos($path, '/v1/redact') === 0;

        return $isRedactEndpoint || true;
    }
```

Is this a bug or do I need to use some other form of authentication for the accounts API?

**Comment by dragonmantank** [comment]
The Account API should be using standard token/secret authentication, and that should be working. I will look into this.

**Comment by dragonmantank** [comment]
Looks like something is up with the API. This doesn't work with a straight cURL call either, so I'll send this up the chain.

**Comment by codegain** [comment]
@dragonmantank After I upgraded to these versions:

```
 - Installing vonage/nexmo-bridge (0.1.0): Downloading (100%)
  - Updating nexmo/client-core (2.2.3 => 2.4.0): Downloading (100%)
  - Updating nexmo/client (2.0.0 => 2.4.0): Downloading (100%)
  - Updating nexmo/laravel (2.2.0 => 2.3.0): Downloading (100%)
```

The error seems to be fixed 👍

**Comment by dragonmantank** [comment]
Good to hear, let me know if you have any more problems!
