### ISSUE TITLE
Add some documentation for the NCCO Builder

### ISSUE THREAD

**Issue by lornajane** [Vonage/vonage-php-sdk-core#251]
## Expected Behavior

Find examples and instructions for the NCCO builder with this repo.

## Current Behavior

No formal documentation, but some examples exist in the [code snippets](https://github.com/Vonage/vonage-php-code-snippets/tree/master/voice).

## Possible Solution

Add a new section to the README to cover this

## Context

I didn't find the builder because it wasn't documented. But now I know, and it is really helpful, so let's help others to understand this approach

**Comment by dominic-ks** [comment]
Hello,

Submitted https://github.com/Vonage/vonage-php-sdk-core/pull/262 for this. 

**NB.** I haven't covered the `connect` and `conversation` actions here as I hadn't managed to do anything with these successfully but I will come back to add them at a later stage if I can.

**Also NB.** I created the PR against my fork initially in error hence the closed PR referenced above.

**Comment by SecondeJK** [comment]
This appears to have been resolved by adding in NCCO examples into readme with #262, closing
