### ISSUE TITLE
[Feature Request] Filter by multiple status values

### ISSUE THREAD

**Issue by rafallyczkowski** [Vonage/vonage-php-sdk-core#258]
I think we are missing filtering calls by array of status values.

Proposed invocation:

`$client->voice()->search((new VoiceFilter())->setStatus([VoiceFilter::STATUS_ANSWERED, VoiceFilter::STATUS_BUSY])`

**Comment by SecondeJK** [comment]
Feature request passed on to Voice API product/engineering for review

**Comment by SecondeJK** [comment]
I'm closing this ticket as the relevant request has been put into the team responsible
