### ISSUE TITLE
Verify setCodeLength error

### ISSUE THREAD

**Issue by mmakler** [Vonage/vonage-php-sdk-core#266]
vonage-php-sdk-core/src/Verify/Request.php
setCodeLength(int $codeLength)

## Expected Behavior
Can be set value 4 or 6.

## Current Behavior
Value cannot be set.

## Possible Solution
Replace OR to AND
```
if ($codeLength !== 4 AND $codeLength !== 6) {
	throw new \InvalidArgumentException('Pin length must be either 4 or 6 digits');
}

$this->codeLength = $codeLength;
return $this;
```

## Steps to Reproduce (for bugs)
setCodeLength(4) - this will throw an error
setCodeLength(6) - this will throw an error

**Comment by dragonmantank** [comment]
Per #261, this was rolled into the basis for the upcoming 2.6.0 release, and will be going out here in a bit. If you still have any issues after the release, let me know!
