### ISSUE TITLE
How to catch Vonage\\Client\\Exception\\Request in Laravel notifications

### ISSUE THREAD

**Issue by szepeviktor** [Vonage/vonage-php-sdk-core#267]
```php
Notification::send($users, new QuizStartedReminder($this->option('channel')));

// In QuizStartedReminder
return (new NexmoMessage)->content('Text of the message');
```

Please advise where/how to catch `Vonage\\Client\\Exception\\Request` in [Laravel](https://laravel.com/docs/8.x/notifications#sms-notifications).
Thank you.

Cc @iamgergo

**Comment by szepeviktor** [comment]
Listening to `Illuminate\Notifications\Events\NotificationFailed` does not work.

**Comment by SecondeJK** [comment]
Update: this is really part of the Laravel integration of how the library works rather than the core PHP SDK. If you're still encountering errors or need guidance, I'd look to raise issues in: https://github.com/laravel/vonage-notification-channel
