### ISSUE TITLE
\Vonage\SMS\InboundSMS::createFromGlobals() doesn't work any more in version 2.4.0

### ISSUE THREAD

**Issue by iceleo-com** [Vonage/vonage-php-sdk-core#268]
I follow the instruction [https://github.com/Vonage/vonage-php-sdk-core#receiving-a-message](https://github.com/Vonage/vonage-php-sdk-core#receiving-a-message) to receive a message from webhook

But the class "**\Vonage\SMS\InboundSMS**" seem to do not exist.

Please check and update new instruction.

Thank you for your hard work!

My PHP version is 7.4.12

**Comment by dragonmantank** [comment]
Thanks! This should be corrected in https://github.com/Vonage/vonage-php-sdk-core/commit/0c293b4649ba7e6ab212b74db9933b81acc399eb

For reference, the code should look like this:

```php
$inbound = \Vonage\SMS\Webhook\Factory::createFromGlobals();
```

If you already have the query parameters or request body you can directly create the object as well, the `Factory` just tries to parse the incoming parameters as best as possible and provides a bunch of different ways to create the object.
