### ISSUE TITLE
Unable to create application user for javascript sdk

### ISSUE THREAD

**Issue by ashish-negi** [Vonage/vonage-php-sdk-core#277]
I am trying to create a new user for browser in-app calling.

`$client->user()->create([ "name" => $name, "display_name" => $display_name]);`

But I am getting the following error:

> Argument 1 passed to Vonage\User\Collection::setFilter() must be an instance of Vonage\Entity\Filter\FilterInterface, instance of Vonage\Client\Factory\MapFactory given

How to create a user using PHP SDK.

**Comment by dragonmantank** [comment]
It looks like we've got an issue automatically pulling the User client in, which is causing the error. I'll see what we can do to get around that.

That being said, the User's API and Conversation API that are currently currently shipped in the PHP SDK are deprecated, and do not match the current beta release of the Conversation API. For example, while I believe creating a user works, it does not retrieve users properly as those endpoints have changed. 

While the Conversations API is in beta, you would be better off using an HTTP client like Guzzle directly to access the API.

**Comment by dragonmantank** [comment]
This should be fixed as of 2.8.1 (though I would still recommend directly hitting the API via Guzzle for full compatibility with the current beta of Conversations).
