### ISSUE TITLE
How to get all received SMS (in the past, not in Live Webhook)

### ISSUE THREAD

**Issue by ttodua** [Vonage/vonage-php-sdk-core#281]
Sorry for probably dull question, but I was unable to find out. 
Any example of PHP code to list messages of all received SMS's?
Including of what is the `$app` (across all examples, different use-cases are shown and I was messed).
So, just a snippet (after "vendor/autoload" line) what code will do that simple job?

**Comment by dragonmantank** [comment]
You would need to use the [Reports API](https://developer.nexmo.com/api/reports) to find information about past SMS messages. As this API is currently in beta it is not available in the SDK itself, so you would need to use Guzzle or another HTTP client to access it. 

You can pull out a PSR-7 compatible HTTP client directly from the Vonage Client, and pass a PSR-7 request through it (most of the time this is Guzzle so you could simplify it some for Guzzle, but the below code is compatible with any PSR-7 HTTP client):

```php
$httpClient = $client->getHttpClient();
$request = new Request($client->getApiUrl() . '/v2/reports/records', 'GET');
$request = $request->withAddedHeader('Authorization', 'Basic ' . base64_encode($apiKey . ':' . $apiSecret));
$request = $request->withUri(
    $request->getUri()->withQuery(
        http_build_query([
            'product' => 'SMS',
            'date_start' => '2021-01-01T00:00Z',
            'direction' => 'inbound',
            'account_id' => $apiKey
        ])
    )
);
$response = $httpClient->sendRequest($request);

var_dump($response->getBody()->getContents());
```

Let me know if this doesn't help!

**Comment by ttodua** [comment]
many thanks! i will try later and post the result here.

**Comment by ttodua** [comment]
Just another example, i'll post it here for historical purposes:

```
public function get_sms($apikey, $secret){
	$query = http_build_query([
		'product' => 'SMS',
		'date_start' => '2021-01-01T00:00Z',
		'direction' => 'inbound',
		'include_message' => 'true',
		'account_id' => $apiKey
	]);
	$response = $this->get_remote_data('https://api.nexmo.com/v2/reports/records?'.$query,null, ['headers'=>['Authorization'=>'Basic ' . base64_encode($apiKey . ':' . $apiSecret)]]);
	return json_decode($response);
}
```
