### ISSUE TITLE
Return value of Vonage\Insights\Basic::getCountryPrefix() must be of the type int, string returned

### ISSUE THREAD

**Issue by ohdonpiano** [Vonage/vonage-php-sdk-core#292]
## Expected Behavior

$number = "+34672117526";
$response = $this->client->insights()->basic($number);
$country_prefix = $response->getCountryPrefix();

## Current Behavior

crash on getCountryPrefix()
Return value of Vonage\Insights\Basic::getCountryPrefix() must be of the type int, string returned

## Possible Solution

current workaround: 
$country_prefix = $response->jsonSerialize()['country_prefix']

## Steps to Reproduce (for bugs)

It happens with some phone numbers

## Your Environment
PHP 7.4
Vonage library 2.4.0

**Comment by SecondeJK** [comment]
Merged, will be released as part of 3.0.0
