### ISSUE TITLE
Missing support for PSR Container 2.0

### ISSUE THREAD

**Issue by miedzikd** [Vonage/vonage-php-sdk-core#306]
The psr/container requirement for this package is "psr/container": "^^1.0", it would be great to support version 2

**Comment by miedzikd** [comment]
We use this library in Symfony 5.4, but when we upgrade to Symfony 6 (that require psr/container 2.0) we have conflict.

> vonage/client-core 2.10.0 requires psr/container ^1.0 -> found psr/container[1.0.0, 1.1.0, 1.1.1, 1.1.2] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by SecondeJK** [comment]
As we have a v3 being released hopefully soon, I'll try and get this in as updating PSR-11 is important.

**Comment by SecondeJK** [comment]
Fixed in #209
