### ISSUE TITLE
SMS sending freezes the execution if throttle occurs

### ISSUE THREAD

**Issue by codewahoo** [Vonage/vonage-php-sdk-core#311]
Line 51 in src/SMS/Client.php calls PHP sleep function, which expects a timeout in seconds, whereas src/SMS/ExceptionErrorHandler.php throws a ThrottleException object with a timeout in milliseconds.
Thus, the script freezes for xxx seconds instead of milliseconds.

**Comment by manavo** [comment]
Looking at `src/SMS/ExceptionErrorHandler.php`, it does seem like it's setting the timeout in seconds now. So this should be resolved?
