### ISSUE TITLE
Encoding problem - type unicode ?

### ISSUE THREAD

**Issue by Dansultan** [Vonage/vonage-php-sdk-core#312]
Hello,

We are nexmo users with postman from a long time,
Lastly we're trying to use a plateform called Ultimate SMS in php 7.4 that use your package to send SMS via the platform.
When we write a sms in plaintext, we're charged like it was unicode 
I hope you could help 
Thanks

**Comment by SecondeJK** [comment]
When creating an SMS object, you can use the method `setType('text)` to set the encoding. As such, this is not an issue as you can also create an SMS as text as well (i.e. `new Vonage\SMS\Message\SMS('from', 'to', 'message content', 'text');`

**Comment by Dansultan** [comment]
Since I've add the setType the type is plain texte and not unicode which is great, but the return to the line doesnt work
