### ISSUE TITLE
Problem with new line since I add setType: text

### ISSUE THREAD

**Issue by Dansultan** [Vonage/vonage-php-sdk-core#316]
Hello, since my last issue with the encoding problem and you told me to add the setType method it worked. But the new line (return) doesn't work anymore

**Comment by Dansultan** [comment]
<img width="674" alt="Capture d’écran 2022-05-04 à 16 02 53" src="https://user-images.githubusercontent.com/80720268/166687554-ddad9a78-3106-4070-adbe-146b0693d686.png">
This is the code I'm using 

If I send 
"Hello,
it's me."
I will receive "Hello,it's me" without the return to the line

**Comment by Dansultan** [comment]
without the new line I mean

**Comment by Dansultan** [comment]
<img width="321" alt="Capture d’écran 2022-05-04 à 16 13 06" src="https://user-images.githubusercontent.com/80720268/166688392-509cca3d-1791-4e0c-9328-a5e97d107d59.png">
I have this parameters associated to the editor I'm using to send

**Comment by SecondeJK** [comment]
I've tried to recreate this, but I can't. This leads me to believe it's an encoding issue. The actual implementation of the code doesn't really matter in this case, it's the variable where the text string is set that I'll need to see

**Comment by SecondeJK** [comment]
This issue is going stale, feel free to reopen when you can provide the code where the variable is set
