### ISSUE TITLE
Remove the dependency on composer/package-versions-deprecated

### ISSUE THREAD

**Issue by jeremyVignelles** [Vonage/vonage-php-sdk-core#345]
This is not a bug or something, I only just saw that this package depends on the deprecated composer/package-versions-deprecated package.

Their [README file](https://github.com/composer/package-versions-deprecated) states:
> This package is EOL / deprecated and you should aim to migrate away from it as soon as possible!

**Comment by SecondeJK** [comment]
Thanks for this - I actually remember writing out this package in a branch that ended up not being merged, so I really should replicate it to pull out the old package and code

**Comment by SecondeJK** [comment]
This has been shipped in 4.0.0

**Comment by ankurk91** [comment]
@SecondeJK 
It is still there
https://github.com/Vonage/vonage-php-sdk-core/blob/aaae3bf0d48ee52e9a3d1760ff62e5530da2bc6f/composer.json#L20

How can you say that?

**Comment by SecondeJK** [comment]
Ah, sorry. The code that uses it has been removed but I forgot to drop the dependency, I'll get that out as a patch today.
