### ISSUE TITLE
Wrong Event Status 

### ISSUE THREAD

**Issue by jBernavaPrah** [Vonage/vonage-php-sdk-core#350]
Hi there!

I'm opening this issue to let you know that in the [line](https://github.com/Vonage/vonage-php-sdk-core/blob/0ef4eeee503f378ffbd432cbef5e65f3b29d5d61/src/Voice/Webhook/Event.php#L34) on the `Event` class under `Vonage\Voice\Webhook` namespace, the STATUS_COMPLETED is wrongly associated to `timeout` instead of `completed`.

**Comment by SecondeJK** [comment]
OK cool, thanks for this I'll check it out

**Comment by SecondeJK** [comment]
Merged, and will be in the next upcoming patch. Thanks for reporting :)
