### ISSUE TITLE
getCallerName/getCallerType throws when CNAM information isn't returned

### ISSUE THREAD

**Issue by dwightwatson** [Vonage/vonage-php-sdk-core#355]
## Expected Behavior
When requesting CNAM insights on a phone number I would expect them to be present. However, if they are not available I'd like to be told that's the case, or at least provided a `null` value.

```php
$response = $vonage->insights()->standardCnam('phone number');

$response->getCallerName();
```

## Current Behavior

Calling `getCallerName()` or `getCallerType()` on the response throws a standard exception about an undefined array key.

```
ErrorException: Undefined array key "caller_name"
```

## Possible Solution
a) Default the values to `null` if they are not available in the response
b) Throw a relevant exception (`CanmUnavilableException` so it can be handled appropriately)
c) Provide `hasCallerName` and `hasCallerType` methods to check presence before attempting to access them

Or this an issue with the endpoint (should CNAM insights always be available on US numbers)?

## Context
My application uses this information for US users. It blows up when the expected data is not in the response.

**Comment by SecondeJK** [comment]
Pushed to main, forthcoming in next release which will be a patch shortly.
