### ISSUE TITLE
Loading V1.8.1 Without Composer

### ISSUE THREAD

**Issue by pihish** [Vonage/vonage-php-sdk-core#356]
## Context
I am working on an older project that runs PHP 5.6.  This project does not have Composer.  I went through the release log and it seems like the 1.8.1 version of the SDK is the last version that supports PHP 5.  I've downloaded the source files for 1.8.1 and put it in a vendor folder.

Which class file should I be loading via `require()` to initialize the SDK?  I am assuming it's **/src/Client.php**.  What are the shapes and types of the parameters that I should pass into for the constructor?   

Is there still online documentation available for 1.8.1?

## Your Environment
Vonage 1.8.1 SDK
PHP 5.6

**Comment by SecondeJK** [comment]
Hi @pihish,
I'm afraid we can't offer support this far back, especially with a PHP version that stopped all support in 2018 and a project that doesn't use Composer. If you do want to use it, it will be the base `src/Client` class, but I couldn't even tell you what the constructor parameters are from back then.
