### ISSUE TITLE
Question: Unable to set language and voice values, other than predefined entry en-US

### ISSUE THREAD

**Issue by inglesuniversal** [Vonage/vonage-php-sdk-core#358]
Latest php SDK installed on an Apache AWS LightSail Server.

    use Vonage\Voice\NCCO\Action\Talk;
    use Vonage\Voice\NCCO\NCCO;
    
    $talk = new Talk('Gracias por su interés en nuestros servicios.', ['voiceName' => 'Lupe', 'language' => 'es-US']);
    $ncco->addAction($talk);

    $outboundCall->setNCCO($ncco);

    $response = $client->voice()->createOutboundCall($outboundCall);

     var_dump($response);
     
     
Example above works fine, but audio is played with default en-US and voice setting (AWS Polly - Kendra)

How do can I force it to play under a different language and voice value?

Kind regards

**Comment by inglesuniversal** [comment]
NOTE: Playing a pre-recorded mp3 file as I was told by your support staff in an Email, makes the whole API not very useful.

**Comment by SecondeJK** [comment]
That isn't particularly useful, no, so apologies for that. And we do have code to set the correct language.
Here's our reference for NCCO objects: https://developer.vonage.com/en/voice/voice-api/concepts/text-to-speech#supported-languages

I'll get a code snippet to you shortly.

**Comment by SecondeJK** [comment]
```
        $talk = new Talk('Gracias por su interés en nuestros servicios.');
        $talk->setLanguage('es-US', 1);

        $ncco->addAction($talk);

        $outboundCall->setNCCO($ncco);

        $response = $client->voice()->createOutboundCall($outboundCall);

        var_dump($response);
```

This should do what you want - the difference is that we now use `setLanguage()` which also takes the style when there are multiple voices (this is why I've added style `1`, it will default to `0` if none specified. This change is because we changed the locale voice identifiers to use a more universal ISO code rather than arbitrary voice names.

**Comment by inglesuniversal** [comment]
Hello @SecondeJK 

Your example above still gave me some 500 error codes when running it, so I made some minor changes and here you have the full working code!


    <?php    

    // https://github.com/Vonage/vonage-php-sdk-core#usage


    require_once "vendor/autoload.php";

    use Vonage\Voice\NCCO\Action\Talk;
    use Vonage\Voice\NCCO\NCCO;


    $keypair = new \Vonage\Client\Credentials\Keypair(
    file_get_contents('./private.key'),
    "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    );

    $client = new \Vonage\Client($keypair);

    $outboundCall = new \Vonage\Voice\OutboundCall(
        new \Vonage\Voice\Endpoint\Phone("99999999999"),
        new \Vonage\Voice\Endpoint\Phone("99999999999")
    );

    $ncco = new NCCO();

    $talk = new Talk('Le informamos que su cuenta ha quedado activada. Gracias por su interés en nuestros servicios.');
    $talk->setLanguage('es-MX', 0);
    $ncco->addAction($talk);

    $outboundCall->setNCCO($ncco);

    $response = $client->voice()->createOutboundCall($outboundCall);

    var_dump($response);
