### ISSUE TITLE
"authentication failed" for /account/get-balance

### ISSUE THREAD

**Issue by codegain** [Vonage/vonage-php-sdk-core#368]
## Expected Behavior

Authentication against https://rest.nexmo.com/account/get-balance works

## Current Behavior

"authentication failed" error after upgrading from 3.1.6 to 4.0.0

## Possible Solution

None

## Steps to Reproduce (for bugs)

1. Use 4.0.0 or the latest version (4.0.6)
2. Call Vonage\Client->accounts()->getBalance()
3. This results in a request made to https://rest.nexmo.com/account/get-balance with an Authorization Basic Header which does use the correct api_key + api_secret
4. Check the response: HTTP 401 - authentication failed
5. Downgrade to 3.1.6
6. Response OK, no http error

## Context

Will stick to 3.1.6 for the moment. Its the second time this call fails for me after upgrading to a new major version (see #243).
This may affect other endpoints under /account as well, at least in my case they aren't working.

## Your Environment

* Version used: 4.0.0/4.0.6
* Environment name and version (e.g. PHP 7.2 on nginx 1.19.1): PHP 8.0 with Apache
* Operating System and version: CentOS 8

**Comment by SecondeJK** [comment]
This is happening because there is only one type of BasicAuth handler, which creates a bearer token.
Under the hood, it needs one for older APIs (like this one) that still send the api key and secret as query parameters.

There will be a pretty quick turnaround for this issue, thank you for reporting.

**Comment by SecondeJK** [comment]
Fixed, thank you for reporting!

**Comment by codegain** [comment]
@SecondeJK Tested the newest release and works for me! Thank you.
