### ISSUE TITLE
Verify API; using Verification for starting a verification is deprecated

### ISSUE THREAD

**Issue by ArkieG** [Vonage/vonage-php-sdk-core#375]
Trying to use Verify but there appears to be a catch 22 situation in the logic behind a deprecation error.

## Expected Behavior
Send a Verify request to the server using this code from the documentation:

```
$request = new \Vonage\Verify\Request('14845551212', 'My App');
$response = $client->verify()->start($request);
echo "Started verification with an id of: " . $response->getRequestId();
```

## Current Behavior

Will always hit this code in Verification.php and generate a deprecation error:

```
trigger_error(
	'Using ' . $this::class . ' for starting a verification is deprecated, ' .
	'please use Vonage\Verify\Request instead',
	E_USER_DEPRECATED
);
```

Because in Client::start this will happen, which converts the Request to array:

```
if ($verification instanceof Request) {
	// Reformat to an array to work with v2.x code, but prep for v3.0.0
	$verification = $verification->toArray();
}

```
And later this:

```
        foreach (['number', 'brand'] as $param) {
            if (!isset($array[$param])) {
                throw new InvalidArgumentException('missing expected key `' . $param . '`');
            }
        }

        $number = $array['number'];
        $brand = $array['brand'];

        unset($array['number'], $array['brand']);

        return @new Verification($number, $brand, $array);
```

Brand is required and the Verification constructor will generate the error whenever brand != null.

## Steps to Reproduce (for bugs)

Just execute the example from the documentation.

Is this by design and is it a requirement to suppress deprecation errors?

**Comment by SecondeJK** [comment]
I've scheduled in time to look at this, to confirm the behaviour.
In the meantime, the deprecation structure is by design - you can switch them off by passing in an an array into the base Client with `show_deprecations` set to false.

**Comment by SecondeJK** [comment]
OK, so I can see what's happening now - the deprecation warnings are there by design, but when I inherited the codebase, v3 or v4 should have taken out that shim to convert the Request object to an array.

I'll make a note that v5 will remove this behaviour, but because it's a B/C change I can't ship the logic rewrite until that point. Thanks for flagging this
