### ISSUE TITLE
Support for Lcobucci JWT 5.0

### ISSUE THREAD

**Issue by Brenneisen** [Vonage/vonage-php-sdk-core#381]
The lcobucci/jwt requirement for this package is "lcobucci/jwt": "^3.4|^4.0", it would be great to support version [v5.0](https://lcobucci-jwt.readthedocs.io/en/stable/upgrading/).

**Comment by SecondeJK** [comment]
No action can be taken right now as v5.0 requires PHP8.1. We will still be supporting PHP8.0 for some time until it's EOL.

**Comment by ankurk91** [comment]
You can allow both versions and handle it

**Comment by SecondeJK** [comment]
```The release v5.0.0 is a modernised version of the library, which requires PHP 8.1+ and drops all the deprecated components.```

I can leave it as is, and things don't break. Or I can introduce something new in the dependency chain when I don't need to, so I'd prefer to just not do that. It's fine if it resolves the correct version to use in PHP, but I am also wary of keeping this stable when unexpected multiple copies of vendor libraries cause weirdness (see: this library's separation from the Guzzle Client)
