### ISSUE TITLE
SMS::isGsm7() incorrectly detects "ç" (U+00E7) as GSM7

### ISSUE THREAD

**Issue by Starfox64** [Vonage/vonage-php-sdk-core#395]
## Expected Behavior
A message containing the character `Latin Small Letter C with Cedilla (U+00E7)` should not be detected as being GSM7 compilent.

## Current Behavior
`SMS::isGsm7()` returns `true` when `Latin Small Letter C with Cedilla (U+00E7)` is present.

## Possible Solution
I've fixed a similar issue last year #318 but it looks like the new regex uses the correct character (capital instead of lowercase) so my guess is that there is something wrong with the regex itself. My suggestion would be to replace the regex implementation with the `EncodingDetector` logic from 3.x.

## Steps to Reproduce (for bugs)
```php
$message = new Vonage\SMS\Message\SMS('+33600000000', 'TEST', 'Hello there ça va ?');
Vonage\SMS\Message\SMS::isGsm7($message->getMessage()); // Returns true despite ç being present
```

## Context
We are migrating to the 4.x release where the Message API was removed, since the `AutoDetect` constructor is missing, we've tried to replace it with this line after creating the SMS:
```php
$message->setType(Vonage\SMS\Message\SMS::isGsm7($message->getMessage()) ? 'text' : 'unicode');
```
The results are wrong however.

## Your Environment
* Version used: 4.1.2
* Environment name and version: PHP 8.1.17
* Operating System and version: Debian 11

**Comment by SecondeJK** [comment]
This will be because of `mb_string` functions and PHP generally being awful with Unicode. I'll look at a workaround for this - the original encoding detector was binned because of edge cases such as this
