### ISSUE TITLE
error Vonage\Verify2\Request\BaseVerifyRequest::setLocale()

### ISSUE THREAD

**Issue by NaVicAn13** [Vonage/vonage-php-sdk-core#428]
please add a line **"return $this;"** to the file Vonage\Verify2\Request\BaseVerifyRequest.php. function setLocale() .

otherwise an error occurs: "Vonage\Verify2\Request\BaseVerifyRequest::setLocale(): Return value must be of type Vonage\Verify2\Request\WhatsAppRequest, none returned".

thanks.

**Comment by SecondeJK** [comment]
Good spot, will go out in patch today

**Comment by SecondeJK** [comment]
Fixed by #429
