### ISSUE TITLE
Vonage server does not send network-code property in DeliveryReceipt JSON Payload

### ISSUE THREAD

**Issue by repli2dev** [Vonage/vonage-php-sdk-core#435]
## Expected Behavior
DeliveryReceipt class should be able to construct the object for payloads that comes in Vonage webooks.

## Current Behavior

`Delivery Receipt missing required data `network-code` on this payload
```
{
"api-key": "<CENSORED>",
"err-code": "7",
"message-timestamp": "2023-09-10 23:20:37",
"messageId": "<UUID>",
"msisdn": "<CENSORED>",
"price": "0",
"scts": "23091012334",
"status": "failed",
"to": "<CENSORED>"
}
```

## Possible Solution
Make the field optionally the same way as `scts` in #416 

## Steps to Reproduce (for bugs)
Attempt to create DeliveryReceipt object from above payload.

## Context
Started od Monday 11 around midnight, we have like 60 of such issues per hour.

## Your Environment
* Version used: 4.3.1
* Environment name and version: PHP 8.2 with nginx
* Operating System and version: Linux Alpine

**Comment by SecondeJK** [comment]
Fixed in #438
