### ISSUE TITLE
Support for PHP 8.3

### ISSUE THREAD

**Issue by Brenneisen** [Vonage/vonage-php-sdk-core#456]
This library uses legacy dependencies. Since PHP 8.3 is now released, a new major version of this library could be released with support for PHP 8.3. To do this, the dependency of lcobucci/jwt 4.0 would have to be extended to 5.1. The support for lcobucci/jwt 3.4 could also be removed, as this version only supports PHP 7.0 anyway.

In addition, the dependency on ramsey/uuid 3.9 should also be extended to 4.0 so that Laravel users can also use this library.

**Comment by SecondeJK** [comment]
I'm closing this because you've duplicated it in a new issue

**Comment by Brenneisen** [comment]
This is not a duplicate. This topic is about support for PHP 8.3.

**Comment by SecondeJK** [comment]
Apologies, I think the mention of the jwt and uuid libraries has got mixed up with the PHP version.
PHP8.3 cannot be supported until Prophecy releases a new 8.3 compatible version.

This will get merged and released when ready, we already have a PR:
https://github.com/Vonage/vonage-php-sdk-core/pull/455

**Comment by SecondeJK** [comment]
Merged #455. More dependency bumps to come.
