### ISSUE TITLE
Subaccount/ClientFactory returns Verify2/Client instead of Subaccount/Client

### ISSUE THREAD

**Issue by shuvalovas** [Vonage/vonage-php-sdk-core#471]
Hello!

Here is the wrong use:
* https://github.com/Vonage/vonage-php-sdk-core/blob/main/src/Subaccount/ClientFactory.php

```
use Vonage\Verify2\Client;
```

It's a mistake I believe. I can create a PR.

**Comment by dragonmantank** [comment]
This is corrected in v4.6.4 which should show up in Packagist soon.

Thanks!
