### ISSUE TITLE
Verify v2 - Call to undefined method Vonage\Client\APIResource::setAuthHandler()

### ISSUE THREAD

**Issue by kissifrot** [Vonage/vonage-php-sdk-core#488]
## Expected Behavior
Verify v2 calls should work

## Current Behavior
Error `Call to undefined method Vonage\Client\APIResource::setAuthHandler()`

## Possible Solution
In src/Verify2/ClientFactory.php just replace calls to `setAuthHandler()` with `setAuthHandlers()` :slightly_smiling_face: 

## Steps to Reproduce (for bugs)
Just run `$client->verify2()->startVerification($verification)`

## Context
Well just tired to implement Verify v2 instead of v1 :slightly_smiling_face: 

## Your Environment
* Version used: 4.8.1
* Environment name and version (e.g. PHP 7.2 on nginx 1.19.1): PHP 8.2
* Operating System and version: irrevelant

**Comment by SecondeJK** [comment]
Release coming shortly

**Comment by SecondeJK** [comment]
Fixed in #489, 4.8.2. Thank you for reporting!
