### ISSUE TITLE
Feature Request - Request IDs Listing

### ISSUE THREAD

**Issue by markatsdp** [Vonage/vonage-php-sdk-core#503]
Hi guys, thanks for an awesome SDK!

I would like to ask if there's a method to list all existing request IDs (or the most recent requestId) based on the phone. I experienced a scenario wherein I missed the opportunity to log or display the request ID and instead kept getting an error message that prevents me from moving forward with the tests: "Concurrent verifications to the same number are not allowed.". I would like to retrieve especially the most recent request ID and use it to either re-check or cancel the request.

Thanks.

**Comment by SecondeJK** [comment]
Hi,
This is a feature that's not currently available, apologies. I have however filed a ticket for discover to see if the Product team on the API can look into opening this up.
