### ISSUE TITLE
Bug when trying to fetch phones: Vonage\Numbers\Filter\OwnedNumbers::setPattern(): Argument #1 ($pattern) must be of type string

### ISSUE THREAD

**Issue by topwebstudio** [Vonage/vonage-php-sdk-core#515]
## Current Behavior

Fatal error as follows: 

Vonage\Numbers\Filter\OwnedNumbers::setPattern(): Argument # 1 ($pattern) must be of type string, Vonage\Numbers\Filter\OwnedNumbers given, called in /var/www/site.com/dev/vendor/vonage/client-core/src/Numbers/Filter/OwnedNumbers.php on line 87
 

## Steps to Reproduce (for bugs)

This is taken directly from the documentation:

      $client = new Client(new Basic($username, $password));
      $filter = new \Vonage\Numbers\Filter\OwnedNumbers();
      $filter->setApplicationId("66c04cea-68b2-45e4-9061-3fd847d627b8");
      $response = $client->numbers()->searchOwned($filter);
      print_r($response);

## Your Environment

* Version used: 4.1.1, but I've tested much older versions too with the same outcome
* Environment name and version: PHP8.3.12

**Comment by SecondeJK** [comment]
Fixed by 4.10.3, thanks for reporting.
